// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\work-contract\unlock\{user}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithUserItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.workContract.unlock.item.item collection</summary>
        /// <param name="position">All months after and including the given one will be unlocked (format: Y-m-d)</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.Item.WithMonthItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.Item.WithMonthItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("month", position);
                return new global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.Item.WithMonthItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract/unlock/{user}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.Item.WithUserItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithUserItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract/unlock/{user}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
