// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Teams.Item.Activities.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Teams.Item.Activities
{
    /// <summary>
    /// Builds and executes requests for operations under \api\teams\{id}\activities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.teams.item.activities.item collection</summary>
        /// <param name="position">The activity to grant acecess to (Activity ID)</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Activities.Item.WithActivityItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Teams.Item.Activities.Item.WithActivityItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("activityId", position);
                return new global::MarkZither.KimaiDotNet.Api.Teams.Item.Activities.Item.WithActivityItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/teams/{id}/activities", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/teams/{id}/activities", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
