// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Absences;
using MarkZither.KimaiDotNet.Api.Actions;
using MarkZither.KimaiDotNet.Api.Activities;
using MarkZither.KimaiDotNet.Api.Config;
using MarkZither.KimaiDotNet.Api.Customers;
using MarkZither.KimaiDotNet.Api.Expenses;
using MarkZither.KimaiDotNet.Api.Export;
using MarkZither.KimaiDotNet.Api.Invoices;
using MarkZither.KimaiDotNet.Api.Kiosk;
using MarkZither.KimaiDotNet.Api.Metafields;
using MarkZither.KimaiDotNet.Api.Ping;
using MarkZither.KimaiDotNet.Api.Plugins;
using MarkZither.KimaiDotNet.Api.Projects;
using MarkZither.KimaiDotNet.Api.PublicHolidays;
using MarkZither.KimaiDotNet.Api.Tags;
using MarkZither.KimaiDotNet.Api.Tasks;
using MarkZither.KimaiDotNet.Api.Teams;
using MarkZither.KimaiDotNet.Api.Timesheets;
using MarkZither.KimaiDotNet.Api.Users;
using MarkZither.KimaiDotNet.Api.VersionNamespace;
using MarkZither.KimaiDotNet.Api.WorkContract;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api
{
    /// <summary>
    /// Builds and executes requests for operations under \api
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ApiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The absences property</summary>
        public global::MarkZither.KimaiDotNet.Api.Absences.AbsencesRequestBuilder Absences
        {
            get => new global::MarkZither.KimaiDotNet.Api.Absences.AbsencesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The actions property</summary>
        public global::MarkZither.KimaiDotNet.Api.Actions.ActionsRequestBuilder Actions
        {
            get => new global::MarkZither.KimaiDotNet.Api.Actions.ActionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The activities property</summary>
        public global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder Activities
        {
            get => new global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The config property</summary>
        public global::MarkZither.KimaiDotNet.Api.Config.ConfigRequestBuilder Config
        {
            get => new global::MarkZither.KimaiDotNet.Api.Config.ConfigRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customers property</summary>
        public global::MarkZither.KimaiDotNet.Api.Customers.CustomersRequestBuilder Customers
        {
            get => new global::MarkZither.KimaiDotNet.Api.Customers.CustomersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The expenses property</summary>
        public global::MarkZither.KimaiDotNet.Api.Expenses.ExpensesRequestBuilder Expenses
        {
            get => new global::MarkZither.KimaiDotNet.Api.Expenses.ExpensesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The export property</summary>
        public global::MarkZither.KimaiDotNet.Api.Export.ExportRequestBuilder Export
        {
            get => new global::MarkZither.KimaiDotNet.Api.Export.ExportRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invoices property</summary>
        public global::MarkZither.KimaiDotNet.Api.Invoices.InvoicesRequestBuilder Invoices
        {
            get => new global::MarkZither.KimaiDotNet.Api.Invoices.InvoicesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The kiosk property</summary>
        public global::MarkZither.KimaiDotNet.Api.Kiosk.KioskRequestBuilder Kiosk
        {
            get => new global::MarkZither.KimaiDotNet.Api.Kiosk.KioskRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The metafields property</summary>
        public global::MarkZither.KimaiDotNet.Api.Metafields.MetafieldsRequestBuilder Metafields
        {
            get => new global::MarkZither.KimaiDotNet.Api.Metafields.MetafieldsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::MarkZither.KimaiDotNet.Api.Ping.PingRequestBuilder Ping
        {
            get => new global::MarkZither.KimaiDotNet.Api.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The plugins property</summary>
        public global::MarkZither.KimaiDotNet.Api.Plugins.PluginsRequestBuilder Plugins
        {
            get => new global::MarkZither.KimaiDotNet.Api.Plugins.PluginsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The projects property</summary>
        public global::MarkZither.KimaiDotNet.Api.Projects.ProjectsRequestBuilder Projects
        {
            get => new global::MarkZither.KimaiDotNet.Api.Projects.ProjectsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The publicHolidays property</summary>
        public global::MarkZither.KimaiDotNet.Api.PublicHolidays.PublicHolidaysRequestBuilder PublicHolidays
        {
            get => new global::MarkZither.KimaiDotNet.Api.PublicHolidays.PublicHolidaysRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tags.TagsRequestBuilder Tags
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tasks property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.TasksRequestBuilder Tasks
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.TasksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The teams property</summary>
        public global::MarkZither.KimaiDotNet.Api.Teams.TeamsRequestBuilder Teams
        {
            get => new global::MarkZither.KimaiDotNet.Api.Teams.TeamsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timesheets property</summary>
        public global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder Timesheets
        {
            get => new global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::MarkZither.KimaiDotNet.Api.Users.UsersRequestBuilder Users
        {
            get => new global::MarkZither.KimaiDotNet.Api.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The version property</summary>
        public global::MarkZither.KimaiDotNet.Api.VersionNamespace.VersionRequestBuilder Version
        {
            get => new global::MarkZither.KimaiDotNet.Api.VersionNamespace.VersionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The workContract property</summary>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.WorkContractRequestBuilder WorkContract
        {
            get => new global::MarkZither.KimaiDotNet.Api.WorkContract.WorkContractRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.ApiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ApiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
