// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.PublicHolidays.Group.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.PublicHolidays.Group
{
    /// <summary>
    /// Builds and executes requests for operations under \api\public-holidays\group
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GroupRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.publicHolidays.group.item collection</summary>
        /// <param name="position">Public holiday group ID to delete</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.PublicHolidays.Group.Item.GroupItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.PublicHolidays.Group.Item.GroupItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::MarkZither.KimaiDotNet.Api.PublicHolidays.Group.Item.GroupItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.PublicHolidays.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public-holidays/group", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.PublicHolidays.Group.GroupRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GroupRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/public-holidays/group", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
