// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Actions.Activity.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Actions.Activity.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\actions\activity\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.actions.activity.item.item collection</summary>
        /// <param name="position">View to display the actions at (e.g. index, custom)</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Activity.Item.Item.WithViewItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Actions.Activity.Item.Item.WithViewItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("view", position);
                return new global::MarkZither.KimaiDotNet.Api.Actions.Activity.Item.Item.WithViewItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Activity.Item.ActivityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions/activity/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Activity.Item.ActivityItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions/activity/{id}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
