// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Activities.Item;
using MarkZither.KimaiDotNet.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MarkZither.KimaiDotNet.Api.Activities
{
    /// <summary>
    /// Builds and executes requests for operations under \api\activities
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivitiesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.activities.item collection</summary>
        /// <param name="position">Activity ID to fetch</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Activities.Item.ActivitiesItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Activities.Item.ActivitiesItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::MarkZither.KimaiDotNet.Api.Activities.Item.ActivitiesItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/activities{?globals*,order*,orderBy*,project*,projects%5B%5D*,term*,visible*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/activities{?globals*,order*,orderBy*,project*,projects%5B%5D*,term*,visible*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch activities
        /// </summary>
        /// <returns>A List&lt;global::MarkZither.KimaiDotNet.Models.ActivityCollection&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::MarkZither.KimaiDotNet.Models.ActivityCollection>?> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder.ActivitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::MarkZither.KimaiDotNet.Models.ActivityCollection>> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder.ActivitiesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::MarkZither.KimaiDotNet.Models.ActivityCollection>(requestInfo, global::MarkZither.KimaiDotNet.Models.ActivityCollection.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates a new activity and returns it afterwards
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.ActivityEntity"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MarkZither.KimaiDotNet.Models.ActivityEntity?> PostAsync(global::MarkZither.KimaiDotNet.Models.ActivityEditForm body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MarkZither.KimaiDotNet.Models.ActivityEntity> PostAsync(global::MarkZither.KimaiDotNet.Models.ActivityEditForm body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MarkZither.KimaiDotNet.Models.ActivityEntity>(requestInfo, global::MarkZither.KimaiDotNet.Models.ActivityEntity.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch activities
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder.ActivitiesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder.ActivitiesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new activity and returns it afterwards
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MarkZither.KimaiDotNet.Models.ActivityEditForm body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MarkZither.KimaiDotNet.Models.ActivityEditForm body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MarkZither.KimaiDotNet.Api.Activities.ActivitiesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch activities
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ActivitiesRequestBuilderGetQueryParameters 
        {
            /// <summary>Use if you want to fetch only global activities. Allowed values: 0|1 (default: 0 for false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("globals")]
            public string? Globals { get; set; }
#nullable restore
#else
            [QueryParameter("globals")]
            public string Globals { get; set; }
#endif
            /// <summary>The result order. Allowed values: ASC, DESC (default: ASC)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>The field by which results will be ordered. Allowed values: id, name, project (default: name)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>Project ID to filter activities</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public string? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public string Project { get; set; }
#endif
            /// <summary>List of project IDs to filter activities, e.g.: projects[]=1&amp;projects[]=2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("projects%5B%5D")]
            public string? Projects { get; set; }
#nullable restore
#else
            [QueryParameter("projects%5B%5D")]
            public string Projects { get; set; }
#endif
            /// <summary>Free search term</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("term")]
            public string? Term { get; set; }
#nullable restore
#else
            [QueryParameter("term")]
            public string Term { get; set; }
#endif
            /// <summary>Visibility status to filter activities: 1=visible, 2=hidden, 3=all</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("visible")]
            public string? Visible { get; set; }
#nullable restore
#else
            [QueryParameter("visible")]
            public string Visible { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
