// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Teams.Item.Members.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Teams.Item.Members
{
    /// <summary>
    /// Builds and executes requests for operations under \api\teams\{id}\members
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MembersRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.teams.item.members.item collection</summary>
        /// <param name="position">The team member to add (User ID)</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Members.Item.WithUserItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Teams.Item.Members.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("userId", position);
                return new global::MarkZither.KimaiDotNet.Api.Teams.Item.Members.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/teams/{id}/members", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Teams.Item.Members.MembersRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MembersRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/teams/{id}/members", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
