// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MarkZither.KimaiDotNet.Api.Absences.Types
{
    /// <summary>
    /// Builds and executes requests for operations under \api\absences\types
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TypesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/absences/types{?language*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TypesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/absences/types{?language*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch absence types
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesGetResponse?> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder.TypesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesGetResponse> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder.TypesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesGetResponse>(requestInfo, global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch absence types
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder.TypesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder.TypesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MarkZither.KimaiDotNet.Api.Absences.Types.TypesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch absence types
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TypesRequestBuilderGetQueryParameters 
        {
            /// <summary>The language to be used for displaying the absences types (format: de or en_GB)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("language")]
            public string? Language { get; set; }
#nullable restore
#else
            [QueryParameter("language")]
            public string Language { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
