// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.WorkContract.Lock;
using MarkZither.KimaiDotNet.Api.WorkContract.Locked;
using MarkZither.KimaiDotNet.Api.WorkContract.Unlock;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.WorkContract
{
    /// <summary>
    /// Builds and executes requests for operations under \api\work-contract
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WorkContractRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lock property</summary>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.LockRequestBuilder Lock
        {
            get => new global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.LockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The locked property</summary>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.Locked.LockedRequestBuilder Locked
        {
            get => new global::MarkZither.KimaiDotNet.Api.WorkContract.Locked.LockedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unlock property</summary>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.UnlockRequestBuilder Unlock
        {
            get => new global::MarkZither.KimaiDotNet.Api.WorkContract.Unlock.UnlockRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.WorkContractRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkContractRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.WorkContractRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WorkContractRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
