// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Tasks.Item.Assign;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Close;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Log;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Meta;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Reopen;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Start;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Stop;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Timesheets;
using MarkZither.KimaiDotNet.Api.Tasks.Item.Unassign;
using MarkZither.KimaiDotNet.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MarkZither.KimaiDotNet.Api.Tasks.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\tasks\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The assign property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Assign.AssignRequestBuilder Assign
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Assign.AssignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The close property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Close.CloseRequestBuilder Close
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Close.CloseRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The log property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Log.LogRequestBuilder Log
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Log.LogRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The meta property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Meta.MetaRequestBuilder Meta
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Meta.MetaRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The reopen property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Reopen.ReopenRequestBuilder Reopen
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Reopen.ReopenRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The start property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Start.StartRequestBuilder Start
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Start.StartRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stop property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Stop.StopRequestBuilder Stop
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Stop.StopRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timesheets property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Timesheets.TimesheetsRequestBuilder Timesheets
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Timesheets.TimesheetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The unassign property</summary>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.Unassign.UnassignRequestBuilder Unassign
        {
            get => new global::MarkZither.KimaiDotNet.Api.Tasks.Item.Unassign.UnassignRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Tasks.Item.TasksItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tasks/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Tasks.Item.TasksItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/tasks/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete task
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch task
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TaskObject"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MarkZither.KimaiDotNet.Models.TaskObject?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MarkZither.KimaiDotNet.Models.TaskObject> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::MarkZither.KimaiDotNet.Models.TaskObject>(requestInfo, global::MarkZither.KimaiDotNet.Models.TaskObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update an existing task, you can pass all or just a subset of all attributes
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TaskObject"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MarkZither.KimaiDotNet.Models.TaskObject?> PatchAsync(global::MarkZither.KimaiDotNet.Models.TaskEditForm body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MarkZither.KimaiDotNet.Models.TaskObject> PatchAsync(global::MarkZither.KimaiDotNet.Models.TaskEditForm body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MarkZither.KimaiDotNet.Models.TaskObject>(requestInfo, global::MarkZither.KimaiDotNet.Models.TaskObject.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete task
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Fetch task
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update an existing task, you can pass all or just a subset of all attributes
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::MarkZither.KimaiDotNet.Models.TaskEditForm body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::MarkZither.KimaiDotNet.Models.TaskEditForm body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Tasks.Item.TasksItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MarkZither.KimaiDotNet.Api.Tasks.Item.TasksItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MarkZither.KimaiDotNet.Api.Tasks.Item.TasksItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
