// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.WorkContract.Lock.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.WorkContract.Lock
{
    /// <summary>
    /// Builds and executes requests for operations under \api\work-contract\lock
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LockRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.workContract.lock.item collection</summary>
        /// <param name="position">The User ID whose entries will be locked</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.Item.WithUserItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.Item.WithUserItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("user", position);
                return new global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.Item.WithUserItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.LockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LockRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract/lock", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.WorkContract.Lock.LockRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LockRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/work-contract/lock", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
