// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Absence : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The date property</summary>
        public DateTimeOffset? Date { get; set; }
        /// <summary>The duration property</summary>
        public int? Duration { get; set; }
        /// <summary>The halfDay property</summary>
        public bool? HalfDay { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.User? User { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.Absence"/> and sets the default values.
        /// </summary>
        public Absence()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = "new";
            Type = "other";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.Absence"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.Absence CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.Absence();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "date", n => { Date = n.GetDateTimeOffsetValue(); } },
                { "duration", n => { Duration = n.GetIntValue(); } },
                { "halfDay", n => { HalfDay = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.User>(global::MarkZither.KimaiDotNet.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("date", Date);
            writer.WriteIntValue("duration", Duration);
            writer.WriteBoolValue("halfDay", HalfDay);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("type", Type);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
