// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AbsenceForm_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "holiday")]
        #pragma warning disable CS1591
        Holiday,
        #pragma warning restore CS1591
        [EnumMember(Value = "time_off")]
        #pragma warning disable CS1591
        Time_off,
        #pragma warning restore CS1591
        [EnumMember(Value = "sickness")]
        #pragma warning disable CS1591
        Sickness,
        #pragma warning restore CS1591
        [EnumMember(Value = "sickness_child")]
        #pragma warning disable CS1591
        Sickness_child,
        #pragma warning restore CS1591
        [EnumMember(Value = "other")]
        #pragma warning disable CS1591
        Other,
        #pragma warning restore CS1591
        [EnumMember(Value = "parental")]
        #pragma warning disable CS1591
        Parental,
        #pragma warning restore CS1591
        [EnumMember(Value = "unpaid_vacation")]
        #pragma warning disable CS1591
        Unpaid_vacation,
        #pragma warning restore CS1591
    }
}
