// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AbsenceForm : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Comment for the absence. Will be visible in the in the absence list.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>Start date of this absence.</summary>
        public Date? Date { get; set; }
        /// <summary>Duration - supports various formats: https://www.kimai.org/documentation/duration-format.html</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Duration { get; set; }
#nullable restore
#else
        public string Duration { get; set; }
#endif
        /// <summary>End date of this absence. This field is not supported by all absence types.</summary>
        public Date? End { get; set; }
        /// <summary>The halfDay property</summary>
        public bool? HalfDay { get; set; }
        /// <summary>The type property</summary>
        public global::MarkZither.KimaiDotNet.Models.AbsenceForm_type? Type { get; set; }
        /// <summary>User ID</summary>
        public int? User { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.AbsenceForm"/> and sets the default values.
        /// </summary>
        public AbsenceForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.AbsenceForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.AbsenceForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.AbsenceForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "date", n => { Date = n.GetDateValue(); } },
                { "duration", n => { Duration = n.GetStringValue(); } },
                { "end", n => { End = n.GetDateValue(); } },
                { "halfDay", n => { HalfDay = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::MarkZither.KimaiDotNet.Models.AbsenceForm_type>(); } },
                { "user", n => { User = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("comment", Comment);
            writer.WriteDateValue("date", Date);
            writer.WriteStringValue("duration", Duration);
            writer.WriteDateValue("end", End);
            writer.WriteBoolValue("halfDay", HalfDay);
            writer.WriteEnumValue<global::MarkZither.KimaiDotNet.Models.AbsenceForm_type>("type", Type);
            writer.WriteIntValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
