// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomerEntity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>The addressLine1 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine1 { get; set; }
#nullable restore
#else
        public string AddressLine1 { get; set; }
#endif
        /// <summary>The addressLine2 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine2 { get; set; }
#nullable restore
#else
        public string AddressLine2 { get; set; }
#endif
        /// <summary>The addressLine3 property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AddressLine3 { get; set; }
#nullable restore
#else
        public string AddressLine3 { get; set; }
#endif
        /// <summary>The billable property</summary>
        public bool? Billable { get; set; }
        /// <summary>The budget property</summary>
        public float? Budget { get; set; }
        /// <summary>The budgetType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BudgetType { get; set; }
#nullable restore
#else
        public string BudgetType { get; set; }
#endif
        /// <summary>The buyerReference property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BuyerReference { get; set; }
#nullable restore
#else
        public string BuyerReference { get; set; }
#endif
        /// <summary>The city property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? City { get; set; }
#nullable restore
#else
        public string City { get; set; }
#endif
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The colorSafe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorSafe { get; set; }
#nullable restore
#else
        public string ColorSafe { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The company property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Company { get; set; }
#nullable restore
#else
        public string Company { get; set; }
#endif
        /// <summary>The contact property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Contact { get; set; }
#nullable restore
#else
        public string Contact { get; set; }
#endif
        /// <summary>The country property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Country { get; set; }
#nullable restore
#else
        public string Country { get; set; }
#endif
        /// <summary>The currency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The fax property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fax { get; set; }
#nullable restore
#else
        public string Fax { get; set; }
#endif
        /// <summary>The homepage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Homepage { get; set; }
#nullable restore
#else
        public string Homepage { get; set; }
#endif
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The metaFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.CustomerMeta>? MetaFields { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.CustomerMeta> MetaFields { get; set; }
#endif
        /// <summary>The mobile property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Mobile { get; set; }
#nullable restore
#else
        public string Mobile { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The phone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Phone { get; set; }
#nullable restore
#else
        public string Phone { get; set; }
#endif
        /// <summary>The postCode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PostCode { get; set; }
#nullable restore
#else
        public string PostCode { get; set; }
#endif
        /// <summary>The teams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.Team>? Teams { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.Team> Teams { get; set; }
#endif
        /// <summary>The timeBudget property</summary>
        public int? TimeBudget { get; set; }
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The vatId property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VatId { get; set; }
#nullable restore
#else
        public string VatId { get; set; }
#endif
        /// <summary>The visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.CustomerEntity"/> and sets the default values.
        /// </summary>
        public CustomerEntity()
        {
            AdditionalData = new Dictionary<string, object>();
            Currency = "EUR";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.CustomerEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.CustomerEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.CustomerEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "addressLine1", n => { AddressLine1 = n.GetStringValue(); } },
                { "addressLine2", n => { AddressLine2 = n.GetStringValue(); } },
                { "addressLine3", n => { AddressLine3 = n.GetStringValue(); } },
                { "billable", n => { Billable = n.GetBoolValue(); } },
                { "budget", n => { Budget = n.GetFloatValue(); } },
                { "budgetType", n => { BudgetType = n.GetStringValue(); } },
                { "buyerReference", n => { BuyerReference = n.GetStringValue(); } },
                { "city", n => { City = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "color-safe", n => { ColorSafe = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "company", n => { Company = n.GetStringValue(); } },
                { "contact", n => { Contact = n.GetStringValue(); } },
                { "country", n => { Country = n.GetStringValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "fax", n => { Fax = n.GetStringValue(); } },
                { "homepage", n => { Homepage = n.GetStringValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "metaFields", n => { MetaFields = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.CustomerMeta>(global::MarkZither.KimaiDotNet.Models.CustomerMeta.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mobile", n => { Mobile = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "phone", n => { Phone = n.GetStringValue(); } },
                { "postCode", n => { PostCode = n.GetStringValue(); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>(global::MarkZither.KimaiDotNet.Models.Team.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timeBudget", n => { TimeBudget = n.GetIntValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "vatId", n => { VatId = n.GetStringValue(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteStringValue("addressLine1", AddressLine1);
            writer.WriteStringValue("addressLine2", AddressLine2);
            writer.WriteStringValue("addressLine3", AddressLine3);
            writer.WriteBoolValue("billable", Billable);
            writer.WriteFloatValue("budget", Budget);
            writer.WriteStringValue("budgetType", BudgetType);
            writer.WriteStringValue("buyerReference", BuyerReference);
            writer.WriteStringValue("city", City);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("color-safe", ColorSafe);
            writer.WriteStringValue("comment", Comment);
            writer.WriteStringValue("company", Company);
            writer.WriteStringValue("contact", Contact);
            writer.WriteStringValue("country", Country);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("fax", Fax);
            writer.WriteStringValue("homepage", Homepage);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.CustomerMeta>("metaFields", MetaFields);
            writer.WriteStringValue("mobile", Mobile);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("phone", Phone);
            writer.WriteStringValue("postCode", PostCode);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>("teams", Teams);
            writer.WriteIntValue("timeBudget", TimeBudget);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("vatId", VatId);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
