// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    /// <summary>The type of budget. Only submit if you want to use a monthly budget.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CustomerEditForm_budgetType
    {
        [EnumMember(Value = "month")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
    }
}
