// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExpenseEditForm : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Activity ID</summary>
        public int? Activity { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The begin property</summary>
        public DateTimeOffset? Begin { get; set; }
        /// <summary>Whether this item should be refundable (yes) or not (no) or if it should be calculated by inherited settings from customer, project and activity (auto).</summary>
        public global::MarkZither.KimaiDotNet.Models.ExpenseEditForm_billableMode? BillableMode { get; set; }
        /// <summary>Cost per entry (multiplied by multiplier). This field is not available to every user.</summary>
        public double? Cost { get; set; }
        /// <summary>Description for the expense</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Expense-Category ID</summary>
        public int? ExpenseCategory { get; set; }
        /// <summary>The exported property</summary>
        public bool? Exported { get; set; }
        /// <summary>The multiplier property</summary>
        public double? Multiplier { get; set; }
        /// <summary>Project ID</summary>
        public int? Project { get; set; }
        /// <summary>User ID</summary>
        public int? User { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.ExpenseEditForm"/> and sets the default values.
        /// </summary>
        public ExpenseEditForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.ExpenseEditForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.ExpenseEditForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.ExpenseEditForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetIntValue(); } },
                { "begin", n => { Begin = n.GetDateTimeOffsetValue(); } },
                { "billableMode", n => { BillableMode = n.GetEnumValue<global::MarkZither.KimaiDotNet.Models.ExpenseEditForm_billableMode>(); } },
                { "cost", n => { Cost = n.GetDoubleValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "expenseCategory", n => { ExpenseCategory = n.GetIntValue(); } },
                { "exported", n => { Exported = n.GetBoolValue(); } },
                { "multiplier", n => { Multiplier = n.GetDoubleValue(); } },
                { "project", n => { Project = n.GetIntValue(); } },
                { "user", n => { User = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activity", Activity);
            writer.WriteDateTimeOffsetValue("begin", Begin);
            writer.WriteEnumValue<global::MarkZither.KimaiDotNet.Models.ExpenseEditForm_billableMode>("billableMode", BillableMode);
            writer.WriteDoubleValue("cost", Cost);
            writer.WriteStringValue("description", Description);
            writer.WriteIntValue("expenseCategory", ExpenseCategory);
            writer.WriteBoolValue("exported", Exported);
            writer.WriteDoubleValue("multiplier", Multiplier);
            writer.WriteIntValue("project", Project);
            writer.WriteIntValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
