// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectEditForm : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billable property</summary>
        public bool? Billable { get; set; }
        /// <summary>The money budget</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public UntypedNode? Budget { get; set; }
#nullable restore
#else
        public UntypedNode Budget { get; set; }
#endif
        /// <summary>The type of budget. Only submit if you want to use a monthly budget.</summary>
        public global::MarkZither.KimaiDotNet.Models.ProjectEditForm_budgetType? BudgetType { get; set; }
        /// <summary>The hexadecimal color code (default: auto-calculated by name)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>Customer ID</summary>
        public int? Customer { get; set; }
        /// <summary>The end property</summary>
        public Date? End { get; set; }
        /// <summary>The globalActivities property</summary>
        public bool? GlobalActivities { get; set; }
        /// <summary>The invoiceText property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InvoiceText { get; set; }
#nullable restore
#else
        public string InvoiceText { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>The orderDate property</summary>
        public Date? OrderDate { get; set; }
        /// <summary>The orderNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderNumber { get; set; }
#nullable restore
#else
        public string OrderNumber { get; set; }
#endif
        /// <summary>The start property</summary>
        public Date? Start { get; set; }
        /// <summary>Array of Team IDs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Teams { get; set; }
#nullable restore
#else
        public List<int?> Teams { get; set; }
#endif
        /// <summary>Duration - supports various formats: https://www.kimai.org/documentation/duration-format.html</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TimeBudget { get; set; }
#nullable restore
#else
        public string TimeBudget { get; set; }
#endif
        /// <summary>The visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.ProjectEditForm"/> and sets the default values.
        /// </summary>
        public ProjectEditForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.ProjectEditForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.ProjectEditForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.ProjectEditForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billable", n => { Billable = n.GetBoolValue(); } },
                { "budget", n => { Budget = n.GetObjectValue<UntypedNode>(UntypedNode.CreateFromDiscriminatorValue); } },
                { "budgetType", n => { BudgetType = n.GetEnumValue<global::MarkZither.KimaiDotNet.Models.ProjectEditForm_budgetType>(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "customer", n => { Customer = n.GetIntValue(); } },
                { "end", n => { End = n.GetDateValue(); } },
                { "globalActivities", n => { GlobalActivities = n.GetBoolValue(); } },
                { "invoiceText", n => { InvoiceText = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "orderDate", n => { OrderDate = n.GetDateValue(); } },
                { "orderNumber", n => { OrderNumber = n.GetStringValue(); } },
                { "start", n => { Start = n.GetDateValue(); } },
                { "teams", n => { Teams = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "timeBudget", n => { TimeBudget = n.GetStringValue(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("billable", Billable);
            writer.WriteObjectValue<UntypedNode>("budget", Budget);
            writer.WriteEnumValue<global::MarkZither.KimaiDotNet.Models.ProjectEditForm_budgetType>("budgetType", BudgetType);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("comment", Comment);
            writer.WriteIntValue("customer", Customer);
            writer.WriteDateValue("end", End);
            writer.WriteBoolValue("globalActivities", GlobalActivities);
            writer.WriteStringValue("invoiceText", InvoiceText);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteDateValue("orderDate", OrderDate);
            writer.WriteStringValue("orderNumber", OrderNumber);
            writer.WriteDateValue("start", Start);
            writer.WriteCollectionOfPrimitiveValues<int?>("teams", Teams);
            writer.WriteStringValue("timeBudget", TimeBudget);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
