// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ProjectCollection : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The billable property</summary>
        public bool? Billable { get; set; }
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The colorSafe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorSafe { get; set; }
#nullable restore
#else
        public string ColorSafe { get; set; }
#endif
        /// <summary>The comment property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Comment { get; set; }
#nullable restore
#else
        public string Comment { get; set; }
#endif
        /// <summary>The customer property</summary>
        public int? Customer { get; set; }
        /// <summary>Attention: Accessor MUST be used, otherwise date will be serialized in UTC.</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>The globalActivities property</summary>
        public bool? GlobalActivities { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The metaFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.ProjectMeta>? MetaFields { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.ProjectMeta> MetaFields { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The number property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>Attention: Accessor MUST be used, otherwise date will be serialized in UTC.</summary>
        public DateTimeOffset? OrderDate { get; set; }
        /// <summary>The orderNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OrderNumber { get; set; }
#nullable restore
#else
        public string OrderNumber { get; set; }
#endif
        /// <summary>The parentTitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ParentTitle { get; set; }
#nullable restore
#else
        public string ParentTitle { get; set; }
#endif
        /// <summary>Attention: Accessor MUST be used, otherwise date will be serialized in UTC.</summary>
        public DateTimeOffset? Start { get; set; }
        /// <summary>The teams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.Team>? Teams { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.Team> Teams { get; set; }
#endif
        /// <summary>The visible property</summary>
        public bool? Visible { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.ProjectCollection"/> and sets the default values.
        /// </summary>
        public ProjectCollection()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.ProjectCollection"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.ProjectCollection CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.ProjectCollection();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billable", n => { Billable = n.GetBoolValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "color-safe", n => { ColorSafe = n.GetStringValue(); } },
                { "comment", n => { Comment = n.GetStringValue(); } },
                { "customer", n => { Customer = n.GetIntValue(); } },
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "globalActivities", n => { GlobalActivities = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "metaFields", n => { MetaFields = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.ProjectMeta>(global::MarkZither.KimaiDotNet.Models.ProjectMeta.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "orderDate", n => { OrderDate = n.GetDateTimeOffsetValue(); } },
                { "orderNumber", n => { OrderNumber = n.GetStringValue(); } },
                { "parentTitle", n => { ParentTitle = n.GetStringValue(); } },
                { "start", n => { Start = n.GetDateTimeOffsetValue(); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>(global::MarkZither.KimaiDotNet.Models.Team.CreateFromDiscriminatorValue)?.AsList(); } },
                { "visible", n => { Visible = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("billable", Billable);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("color-safe", ColorSafe);
            writer.WriteStringValue("comment", Comment);
            writer.WriteIntValue("customer", Customer);
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteBoolValue("globalActivities", GlobalActivities);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.ProjectMeta>("metaFields", MetaFields);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("number", Number);
            writer.WriteDateTimeOffsetValue("orderDate", OrderDate);
            writer.WriteStringValue("orderNumber", OrderNumber);
            writer.WriteStringValue("parentTitle", ParentTitle);
            writer.WriteDateTimeOffsetValue("start", Start);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>("teams", Teams);
            writer.WriteBoolValue("visible", Visible);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
