// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TaskObject : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activeTimesheets property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.TimesheetExpanded>? ActiveTimesheets { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.TimesheetExpanded> ActiveTimesheets { get; set; }
#endif
        /// <summary>The activity property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.ActivityExpanded? Activity { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.ActivityExpanded Activity { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The end property</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>The estimation property</summary>
        public int? Estimation { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The metaFields property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.TaskMeta>? MetaFields { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.TaskMeta> MetaFields { get; set; }
#endif
        /// <summary>The project property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.ProjectExpanded? Project { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.ProjectExpanded Project { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The team property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.Team? Team { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.Team Team { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The todo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Todo { get; set; }
#nullable restore
#else
        public string Todo { get; set; }
#endif
        /// <summary>The user property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.User? User { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.User User { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.TaskObject"/> and sets the default values.
        /// </summary>
        public TaskObject()
        {
            AdditionalData = new Dictionary<string, object>();
            Status = "pending";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TaskObject"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.TaskObject CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.TaskObject();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activeTimesheets", n => { ActiveTimesheets = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TimesheetExpanded>(global::MarkZither.KimaiDotNet.Models.TimesheetExpanded.CreateFromDiscriminatorValue)?.AsList(); } },
                { "activity", n => { Activity = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.ActivityExpanded>(global::MarkZither.KimaiDotNet.Models.ActivityExpanded.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "estimation", n => { Estimation = n.GetIntValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "metaFields", n => { MetaFields = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TaskMeta>(global::MarkZither.KimaiDotNet.Models.TaskMeta.CreateFromDiscriminatorValue)?.AsList(); } },
                { "project", n => { Project = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.ProjectExpanded>(global::MarkZither.KimaiDotNet.Models.ProjectExpanded.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "team", n => { Team = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.Team>(global::MarkZither.KimaiDotNet.Models.Team.CreateFromDiscriminatorValue); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "todo", n => { Todo = n.GetStringValue(); } },
                { "user", n => { User = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.User>(global::MarkZither.KimaiDotNet.Models.User.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TimesheetExpanded>("activeTimesheets", ActiveTimesheets);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.ActivityExpanded>("activity", Activity);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteIntValue("estimation", Estimation);
            writer.WriteIntValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TaskMeta>("metaFields", MetaFields);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.ProjectExpanded>("project", Project);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.Team>("team", Team);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("todo", Todo);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.User>("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
