// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimesheetEditForm : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Activity ID</summary>
        public int? Activity { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>If no begin date-time is set, the users current timestamp will be used</summary>
        public DateTimeOffset? Begin { get; set; }
        /// <summary>The billable property</summary>
        public bool? Billable { get; set; }
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>If no end date-time is set, the timesheet will be running</summary>
        public DateTimeOffset? End { get; set; }
        /// <summary>The exported property</summary>
        public bool? Exported { get; set; }
        /// <summary>Fixed rate</summary>
        public double? FixedRate { get; set; }
        /// <summary>Hourly rate</summary>
        public double? HourlyRate { get; set; }
        /// <summary>Project ID</summary>
        public int? Project { get; set; }
        /// <summary>Comma separated list of tags</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Tags { get; set; }
#nullable restore
#else
        public string Tags { get; set; }
#endif
        /// <summary>User ID</summary>
        public int? User { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.TimesheetEditForm"/> and sets the default values.
        /// </summary>
        public TimesheetEditForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TimesheetEditForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.TimesheetEditForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.TimesheetEditForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activity", n => { Activity = n.GetIntValue(); } },
                { "begin", n => { Begin = n.GetDateTimeOffsetValue(); } },
                { "billable", n => { Billable = n.GetBoolValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "end", n => { End = n.GetDateTimeOffsetValue(); } },
                { "exported", n => { Exported = n.GetBoolValue(); } },
                { "fixedRate", n => { FixedRate = n.GetDoubleValue(); } },
                { "hourlyRate", n => { HourlyRate = n.GetDoubleValue(); } },
                { "project", n => { Project = n.GetIntValue(); } },
                { "tags", n => { Tags = n.GetStringValue(); } },
                { "user", n => { User = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activity", Activity);
            writer.WriteDateTimeOffsetValue("begin", Begin);
            writer.WriteBoolValue("billable", Billable);
            writer.WriteStringValue("description", Description);
            writer.WriteDateTimeOffsetValue("end", End);
            writer.WriteBoolValue("exported", Exported);
            writer.WriteDoubleValue("fixedRate", FixedRate);
            writer.WriteDoubleValue("hourlyRate", HourlyRate);
            writer.WriteIntValue("project", Project);
            writer.WriteStringValue("tags", Tags);
            writer.WriteIntValue("user", User);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
