// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TimesheetConfig : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The activeEntriesHardLimit property</summary>
        public int? ActiveEntriesHardLimit { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The defaultBeginTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultBeginTime { get; set; }
#nullable restore
#else
        public string DefaultBeginTime { get; set; }
#endif
        /// <summary>The isAllowFutureTimes property</summary>
        public bool? IsAllowFutureTimes { get; set; }
        /// <summary>The isAllowOverlapping property</summary>
        public bool? IsAllowOverlapping { get; set; }
        /// <summary>The trackingMode property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingMode { get; set; }
#nullable restore
#else
        public string TrackingMode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.TimesheetConfig"/> and sets the default values.
        /// </summary>
        public TimesheetConfig()
        {
            AdditionalData = new Dictionary<string, object>();
            DefaultBeginTime = "now";
            TrackingMode = "default";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TimesheetConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.TimesheetConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.TimesheetConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "activeEntriesHardLimit", n => { ActiveEntriesHardLimit = n.GetIntValue(); } },
                { "defaultBeginTime", n => { DefaultBeginTime = n.GetStringValue(); } },
                { "isAllowFutureTimes", n => { IsAllowFutureTimes = n.GetBoolValue(); } },
                { "isAllowOverlapping", n => { IsAllowOverlapping = n.GetBoolValue(); } },
                { "trackingMode", n => { TrackingMode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("activeEntriesHardLimit", ActiveEntriesHardLimit);
            writer.WriteStringValue("defaultBeginTime", DefaultBeginTime);
            writer.WriteBoolValue("isAllowFutureTimes", IsAllowFutureTimes);
            writer.WriteBoolValue("isAllowOverlapping", IsAllowOverlapping);
            writer.WriteStringValue("trackingMode", TrackingMode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
