// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserEditForm : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alias property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The hexadecimal color code (default: auto-calculated by name)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The language property</summary>
        public global::MarkZither.KimaiDotNet.Models.UserEditForm_language? Language { get; set; }
        /// <summary>The locale property</summary>
        public global::MarkZither.KimaiDotNet.Models.UserEditForm_locale? Locale { get; set; }
        /// <summary>The requiresPasswordReset property</summary>
        public bool? RequiresPasswordReset { get; set; }
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.UserEditForm_roles?>? Roles { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.UserEditForm_roles?> Roles { get; set; }
#endif
        /// <summary>User ID</summary>
        public int? Supervisor { get; set; }
        /// <summary>The systemAccount property</summary>
        public bool? SystemAccount { get; set; }
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.UserEditForm"/> and sets the default values.
        /// </summary>
        public UserEditForm()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.UserEditForm"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.UserEditForm CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.UserEditForm();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountNumber", n => { AccountNumber = n.GetStringValue(); } },
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "language", n => { Language = n.GetEnumValue<global::MarkZither.KimaiDotNet.Models.UserEditForm_language>(); } },
                { "locale", n => { Locale = n.GetEnumValue<global::MarkZither.KimaiDotNet.Models.UserEditForm_locale>(); } },
                { "requiresPasswordReset", n => { RequiresPasswordReset = n.GetBoolValue(); } },
                { "roles", n => { Roles = n.GetCollectionOfEnumValues<global::MarkZither.KimaiDotNet.Models.UserEditForm_roles>()?.AsList(); } },
                { "supervisor", n => { Supervisor = n.GetIntValue(); } },
                { "systemAccount", n => { SystemAccount = n.GetBoolValue(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountNumber", AccountNumber);
            writer.WriteStringValue("alias", Alias);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteEnumValue<global::MarkZither.KimaiDotNet.Models.UserEditForm_language>("language", Language);
            writer.WriteEnumValue<global::MarkZither.KimaiDotNet.Models.UserEditForm_locale>("locale", Locale);
            writer.WriteBoolValue("requiresPasswordReset", RequiresPasswordReset);
            writer.WriteCollectionOfEnumValues<global::MarkZither.KimaiDotNet.Models.UserEditForm_roles>("roles", Roles);
            writer.WriteIntValue("supervisor", Supervisor);
            writer.WriteBoolValue("systemAccount", SystemAccount);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("title", Title);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
