// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UserEntity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accountNumber property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountNumber { get; set; }
#nullable restore
#else
        public string AccountNumber { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The alias property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>DEPRECATED - switch to API tokens instead</summary>
        [Obsolete("")]
        public bool? ApiToken { get; set; }
        /// <summary>The avatar property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Avatar { get; set; }
#nullable restore
#else
        public string Avatar { get; set; }
#endif
        /// <summary>The color property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The colorSafe property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ColorSafe { get; set; }
#nullable restore
#else
        public string ColorSafe { get; set; }
#endif
        /// <summary>The email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>The enabled property</summary>
        public bool? Enabled { get; set; }
        /// <summary>The id property</summary>
        public int? Id { get; set; }
        /// <summary>The initials property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Initials { get; set; }
#nullable restore
#else
        public string Initials { get; set; }
#endif
        /// <summary>The language property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The locale property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Locale { get; set; }
#nullable restore
#else
        public string Locale { get; set; }
#endif
        /// <summary>The memberships property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.TeamMembership>? Memberships { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.TeamMembership> Memberships { get; set; }
#endif
        /// <summary>The preferences property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.UserPreference>? Preferences { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.UserPreference> Preferences { get; set; }
#endif
        /// <summary>The roles property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Roles { get; set; }
#nullable restore
#else
        public List<string> Roles { get; set; }
#endif
        /// <summary>The supervisor property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::MarkZither.KimaiDotNet.Models.User? Supervisor { get; set; }
#nullable restore
#else
        public global::MarkZither.KimaiDotNet.Models.User Supervisor { get; set; }
#endif
        /// <summary>The systemAccount property</summary>
        public bool? SystemAccount { get; set; }
        /// <summary>The teams property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::MarkZither.KimaiDotNet.Models.Team>? Teams { get; set; }
#nullable restore
#else
        public List<global::MarkZither.KimaiDotNet.Models.Team> Teams { get; set; }
#endif
        /// <summary>The timezone property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Timezone { get; set; }
#nullable restore
#else
        public string Timezone { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The username property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Username { get; set; }
#nullable restore
#else
        public string Username { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Models.UserEntity"/> and sets the default values.
        /// </summary>
        public UserEntity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.UserEntity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::MarkZither.KimaiDotNet.Models.UserEntity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::MarkZither.KimaiDotNet.Models.UserEntity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountNumber", n => { AccountNumber = n.GetStringValue(); } },
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "apiToken", n => { ApiToken = n.GetBoolValue(); } },
                { "avatar", n => { Avatar = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "color-safe", n => { ColorSafe = n.GetStringValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "initials", n => { Initials = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "locale", n => { Locale = n.GetStringValue(); } },
                { "memberships", n => { Memberships = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TeamMembership>(global::MarkZither.KimaiDotNet.Models.TeamMembership.CreateFromDiscriminatorValue)?.AsList(); } },
                { "preferences", n => { Preferences = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.UserPreference>(global::MarkZither.KimaiDotNet.Models.UserPreference.CreateFromDiscriminatorValue)?.AsList(); } },
                { "roles", n => { Roles = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "supervisor", n => { Supervisor = n.GetObjectValue<global::MarkZither.KimaiDotNet.Models.User>(global::MarkZither.KimaiDotNet.Models.User.CreateFromDiscriminatorValue); } },
                { "systemAccount", n => { SystemAccount = n.GetBoolValue(); } },
                { "teams", n => { Teams = n.GetCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>(global::MarkZither.KimaiDotNet.Models.Team.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timezone", n => { Timezone = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountNumber", AccountNumber);
            writer.WriteStringValue("alias", Alias);
            writer.WriteBoolValue("apiToken", ApiToken);
            writer.WriteStringValue("avatar", Avatar);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("color-safe", ColorSafe);
            writer.WriteStringValue("email", Email);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("initials", Initials);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("locale", Locale);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.TeamMembership>("memberships", Memberships);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.UserPreference>("preferences", Preferences);
            writer.WriteCollectionOfPrimitiveValues<string>("roles", Roles);
            writer.WriteObjectValue<global::MarkZither.KimaiDotNet.Models.User>("supervisor", Supervisor);
            writer.WriteBoolValue("systemAccount", SystemAccount);
            writer.WriteCollectionOfObjectValues<global::MarkZither.KimaiDotNet.Models.Team>("teams", Teams);
            writer.WriteStringValue("timezone", Timezone);
            writer.WriteStringValue("title", Title);
            writer.WriteStringValue("username", Username);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
