// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace MarkZither.KimaiDotNet.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum UserEditForm_roles
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ROLE_TEAMLEAD")]
        #pragma warning disable CS1591
        ROLE_TEAMLEAD,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLE_ADMIN")]
        #pragma warning disable CS1591
        ROLE_ADMIN,
        #pragma warning restore CS1591
        [EnumMember(Value = "ROLE_SUPER_ADMIN")]
        #pragma warning disable CS1591
        ROLE_SUPER_ADMIN,
        #pragma warning restore CS1591
    }
}
