// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \api\actions\project\{id}\{view}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithViewItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.actions.project.item.item.item collection</summary>
        /// <param name="position">Language to translate the action title to (e.g. de, en)</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.Item.WithLocaleItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.Item.WithLocaleItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("locale", position);
                return new global::MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.Item.WithLocaleItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.WithViewItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithViewItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions/project/{id}/{view}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.Project.Item.Item.WithViewItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithViewItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions/project/{id}/{view}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
