// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Config.Colors;
using MarkZither.KimaiDotNet.Api.Config.Timesheet;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Config
{
    /// <summary>
    /// Builds and executes requests for operations under \api\config
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ConfigRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The colors property</summary>
        public global::MarkZither.KimaiDotNet.Api.Config.Colors.ColorsRequestBuilder Colors
        {
            get => new global::MarkZither.KimaiDotNet.Api.Config.Colors.ColorsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timesheet property</summary>
        public global::MarkZither.KimaiDotNet.Api.Config.Timesheet.TimesheetRequestBuilder Timesheet
        {
            get => new global::MarkZither.KimaiDotNet.Api.Config.Timesheet.TimesheetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/config", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Config.ConfigRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ConfigRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/config", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
