// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Actions.Activity;
using MarkZither.KimaiDotNet.Api.Actions.Customer;
using MarkZither.KimaiDotNet.Api.Actions.Project;
using MarkZither.KimaiDotNet.Api.Actions.Timesheet;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace MarkZither.KimaiDotNet.Api.Actions
{
    /// <summary>
    /// Builds and executes requests for operations under \api\actions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activity property</summary>
        public global::MarkZither.KimaiDotNet.Api.Actions.Activity.ActivityRequestBuilder Activity
        {
            get => new global::MarkZither.KimaiDotNet.Api.Actions.Activity.ActivityRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The customer property</summary>
        public global::MarkZither.KimaiDotNet.Api.Actions.Customer.CustomerRequestBuilder Customer
        {
            get => new global::MarkZither.KimaiDotNet.Api.Actions.Customer.CustomerRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The project property</summary>
        public global::MarkZither.KimaiDotNet.Api.Actions.Project.ProjectRequestBuilder Project
        {
            get => new global::MarkZither.KimaiDotNet.Api.Actions.Project.ProjectRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The timesheet property</summary>
        public global::MarkZither.KimaiDotNet.Api.Actions.Timesheet.TimesheetRequestBuilder Timesheet
        {
            get => new global::MarkZither.KimaiDotNet.Api.Actions.Timesheet.TimesheetRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Actions.ActionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/actions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
