// <auto-generated/>
#pragma warning disable CS0618
using MarkZither.KimaiDotNet.Api.Timesheets.Active;
using MarkZither.KimaiDotNet.Api.Timesheets.Item;
using MarkZither.KimaiDotNet.Api.Timesheets.Recent;
using MarkZither.KimaiDotNet.Models;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace MarkZither.KimaiDotNet.Api.Timesheets
{
    /// <summary>
    /// Builds and executes requests for operations under \api\timesheets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TimesheetsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The active property</summary>
        public global::MarkZither.KimaiDotNet.Api.Timesheets.Active.ActiveRequestBuilder Active
        {
            get => new global::MarkZither.KimaiDotNet.Api.Timesheets.Active.ActiveRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The recent property</summary>
        public global::MarkZither.KimaiDotNet.Api.Timesheets.Recent.RecentRequestBuilder Recent
        {
            get => new global::MarkZither.KimaiDotNet.Api.Timesheets.Recent.RecentRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>Gets an item from the MarkZither.KimaiDotNet.api.timesheets.item collection</summary>
        /// <param name="position">Timesheet ID to fetch</param>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Timesheets.Item.TimesheetsItemRequestBuilder"/></returns>
        public global::MarkZither.KimaiDotNet.Api.Timesheets.Item.TimesheetsItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::MarkZither.KimaiDotNet.Api.Timesheets.Item.TimesheetsItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimesheetsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/timesheets{?active*,activities%5B%5D*,activity*,begin*,billable*,customer*,customers%5B%5D*,end*,exported*,full*,modified_after*,order*,orderBy*,page*,project*,projects%5B%5D*,size*,tags%5B%5D*,term*,user*,users%5B%5D*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TimesheetsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/api/timesheets{?active*,activities%5B%5D*,activity*,begin*,billable*,customer*,customers%5B%5D*,end*,exported*,full*,modified_after*,order*,orderBy*,page*,project*,projects%5B%5D*,size*,tags%5B%5D*,term*,user*,users%5B%5D*}", rawUrl)
        {
        }
        /// <summary>
        /// Fetch timesheets
        /// </summary>
        /// <returns>A List&lt;global::MarkZither.KimaiDotNet.Models.TimesheetCollection&gt;</returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<List<global::MarkZither.KimaiDotNet.Models.TimesheetCollection>?> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<List<global::MarkZither.KimaiDotNet.Models.TimesheetCollection>> GetAsync(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var collectionResult = await RequestAdapter.SendCollectionAsync<global::MarkZither.KimaiDotNet.Models.TimesheetCollection>(requestInfo, global::MarkZither.KimaiDotNet.Models.TimesheetCollection.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
            return collectionResult?.AsList();
        }
        /// <summary>
        /// Creates a new timesheet for the current user and returns it afterwards.
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Models.TimesheetEntity"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::MarkZither.KimaiDotNet.Models.TimesheetEntity?> PostAsync(global::MarkZither.KimaiDotNet.Models.TimesheetEditForm body, Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderPostQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::MarkZither.KimaiDotNet.Models.TimesheetEntity> PostAsync(global::MarkZither.KimaiDotNet.Models.TimesheetEditForm body, Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderPostQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::MarkZither.KimaiDotNet.Models.TimesheetEntity>(requestInfo, global::MarkZither.KimaiDotNet.Models.TimesheetEntity.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Fetch timesheets
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Creates a new timesheet for the current user and returns it afterwards.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::MarkZither.KimaiDotNet.Models.TimesheetEditForm body, Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderPostQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::MarkZither.KimaiDotNet.Models.TimesheetEditForm body, Action<RequestConfiguration<global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder.TimesheetsRequestBuilderPostQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::MarkZither.KimaiDotNet.Api.Timesheets.TimesheetsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Fetch timesheets
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TimesheetsRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter for running/active records. Allowed values: 0=stopped, 1=active (default: all)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("active")]
            public string? Active { get; set; }
#nullable restore
#else
            [QueryParameter("active")]
            public string Active { get; set; }
#endif
            /// <summary>List of activity IDs to filter, e.g.: activities[]=1&amp;activities[]=2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("activities%5B%5D")]
            public string? Activities { get; set; }
#nullable restore
#else
            [QueryParameter("activities%5B%5D")]
            public string Activities { get; set; }
#endif
            /// <summary>Activity ID to filter timesheets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("activity")]
            public string? Activity { get; set; }
#nullable restore
#else
            [QueryParameter("activity")]
            public string Activity { get; set; }
#endif
            /// <summary>Only records started at or after this date-time will be included (format: HTML5 datetime-local, e.g. YYYY-MM-DDThh:mm:ss)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("begin")]
            public string? Begin { get; set; }
#nullable restore
#else
            [QueryParameter("begin")]
            public string Begin { get; set; }
#endif
            /// <summary>Filter for non-/billable records. Allowed values: 0=non-billable, 1=billable (default: all)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("billable")]
            public string? Billable { get; set; }
#nullable restore
#else
            [QueryParameter("billable")]
            public string Billable { get; set; }
#endif
            /// <summary>Customer ID to filter timesheets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("customer")]
            public string? Customer { get; set; }
#nullable restore
#else
            [QueryParameter("customer")]
            public string Customer { get; set; }
#endif
            /// <summary>List of customer IDs to filter, e.g.: customers[]=1&amp;customers[]=2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("customers%5B%5D")]
            public string? Customers { get; set; }
#nullable restore
#else
            [QueryParameter("customers%5B%5D")]
            public string Customers { get; set; }
#endif
            /// <summary>Only records started at or before this date-time will be included (format: HTML5 datetime-local, e.g. YYYY-MM-DDThh:mm:ss)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end")]
            public string? End { get; set; }
#nullable restore
#else
            [QueryParameter("end")]
            public string End { get; set; }
#endif
            /// <summary>Use this flag if you want to filter for export state. Allowed values: 0=not exported, 1=exported (default: all)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("exported")]
            public string? Exported { get; set; }
#nullable restore
#else
            [QueryParameter("exported")]
            public string Exported { get; set; }
#endif
            /// <summary>Allows to fetch full objects including subresources. Allowed values: 0|1|false|true (default: false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("full")]
            public string? Full { get; set; }
#nullable restore
#else
            [QueryParameter("full")]
            public string Full { get; set; }
#endif
            /// <summary>Only records changed after this date will be included. You need to pass in a UTC date-time, as this field is stored in UTC (format: HTML5 datetime-local, e.g. YYYY-MM-DDThh:mm:ss)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("modified_after")]
            public string? ModifiedAfter { get; set; }
#nullable restore
#else
            [QueryParameter("modified_after")]
            public string ModifiedAfter { get; set; }
#endif
            /// <summary>The result order. Allowed values: ASC, DESC (default: DESC)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            /// <summary>The field by which results will be ordered. Allowed values: id, begin, end, rate (default: begin)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("orderBy")]
            public string? OrderBy { get; set; }
#nullable restore
#else
            [QueryParameter("orderBy")]
            public string OrderBy { get; set; }
#endif
            /// <summary>The page to display, renders a 404 if not found (default: 1)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page")]
            public string? Page { get; set; }
#nullable restore
#else
            [QueryParameter("page")]
            public string Page { get; set; }
#endif
            /// <summary>Project ID to filter timesheets</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("project")]
            public string? Project { get; set; }
#nullable restore
#else
            [QueryParameter("project")]
            public string Project { get; set; }
#endif
            /// <summary>List of project IDs to filter, e.g.: projects[]=1&amp;projects[]=2</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("projects%5B%5D")]
            public string? Projects { get; set; }
#nullable restore
#else
            [QueryParameter("projects%5B%5D")]
            public string Projects { get; set; }
#endif
            /// <summary>The amount of entries for each page (default: 50, max: 500)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("size")]
            public string? Size { get; set; }
#nullable restore
#else
            [QueryParameter("size")]
            public string Size { get; set; }
#endif
            /// <summary>List of tag names, e.g. tags[]=bar&amp;tags[]=foo</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tags%5B%5D")]
            public string? Tags { get; set; }
#nullable restore
#else
            [QueryParameter("tags%5B%5D")]
            public string Tags { get; set; }
#endif
            /// <summary>Free search term</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("term")]
            public string? Term { get; set; }
#nullable restore
#else
            [QueryParameter("term")]
            public string Term { get; set; }
#endif
            /// <summary>User ID to filter timesheets. Needs permission &apos;view_other_timesheet&apos;, pass &apos;all&apos; to fetch data for all user (default: current user)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user")]
            public string? User { get; set; }
#nullable restore
#else
            [QueryParameter("user")]
            public string User { get; set; }
#endif
            /// <summary>List of user IDs to filter, e.g.: users[]=1&amp;users[]=2 (ignored if user=all)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("users%5B%5D")]
            public string? Users { get; set; }
#nullable restore
#else
            [QueryParameter("users%5B%5D")]
            public string Users { get; set; }
#endif
        }
        /// <summary>
        /// Creates a new timesheet for the current user and returns it afterwards.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TimesheetsRequestBuilderPostQueryParameters 
        {
            /// <summary>Allows to fetch fully serialized objects including subresources (TimesheetExpanded). Allowed values: true (default: false)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("full")]
            public string? Full { get; set; }
#nullable restore
#else
            [QueryParameter("full")]
            public string Full { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
